worker_processes 1;

events {
    worker_connections 1024;
}

http {

    server {
        listen 8080;
        server_name localhost;

        root C:/Users/EFG/Downloads/nginx-1.31.3/nginx-1.31.3/html/sites/tech;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }

    server {
        listen 8081;
        server_name localhost;

        root C:/Users/EFG/Downloads/nginx-1.31.3/nginx-1.31.3/html/sites/suporte;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
